services:
  openwebrx-telegram-bot:
    image: slechev/openwebrx-telegram-bot
    env_file:
      - .env
    volumes:
      - /tmp/geoip:/tmp/geoip
      - /tmp/owrx-bot:/data
    restart: unless-stopped